---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Music
  - Notes
  - Reminders
  - Contacts
  - Calandar
  - Facetime
  - Photos
  - Maps
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

fonts:
  - name: Monoid
    archive: https://github.com/jb-dmitry/monoid.git
    version: master
    directory: Monoisome
    files:
      - Monoisome-Regular.ttf
  - name: Meslo LG M for Powerline
    archive: https://github.com/powerline/fonts.git
    version: master
    directory: "Meslo Slashed"
    files:
      - Meslo LG L Bold Italic for Powerline.ttf
      - Meslo LG L Bold for Powerline.ttf
      - Meslo LG L Italic for Powerline.ttf
      - Meslo LG L Regular for Powerline.ttf
      - Meslo LG M Bold Italic for Powerline.ttf
      - Meslo LG M Bold for Powerline.ttf
      - Meslo LG M Italic for Powerline.ttf
      - Meslo LG M Regular for Powerline.ttf
      - Meslo LG S Bold Italic for Powerline.ttf
      - Meslo LG S Bold for Powerline.ttf
      - Meslo LG S Italic for Powerline.ttf
      - Meslo LG S Regular for Powerline.ttf

dotfiles_repo: https://github.com/DamianFlynn/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Developer/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .aliases
  - .p10k.zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-versions
  - azure/bicep

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - mcrypt
  - nmap
  - node
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search
  - azure-cli
  # - azure-functions-core-tools@3
  - brew-cask-completion
  - curl
  - exiftool
  - flux
  - packer
  - hugo
  - jq
  - helm
  - kompose
  - telnet
  - k9s
  - terraform
  - kubernetes-cli
  # - unrar
  - tmux
  - mas
  # tap: homebrew/cask-versions
  - bicep

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - iterm2
  - google-chrome
  - vagrant
  - microsoft-teams
  - powershell
  - microsoft-edge
  - visual-studio-code
  - obsidian

  # tap: homebrew/cask-drivers
  - elgato-stream-deck
  - elgato-wave-link
  - hdhomerun
  # - yubico-authenticator
  - yubico-yubikey-manager
  # - yubico-yubikey-personalization-gui
  # - yubico-yubikey-piv-manager
  # - bose-updater
  
  # tap: homebrew/cask-versions
  - 1password-beta
  - 1password-cli-beta


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 1290358394, name: "Cardhop"}
  # - { id: 975937182, name: "Fantastical - Calendar"}
  - { id: 1455214828, name: "MQTT Explorer"}
  - { id: 462054704, name: "Microsoft Word"}
  - { id: 462062816, name:  "Microsoft PowerPoint"}
  - { id: 462058435, name: "Microsoft Excel"}
  - { id: 985367838, name: "Microsoft Outlook"}
  - { id: 823766827, name: "OneDrive"}
  - { id: 1327661892, name: "XMind: Mind Mapping"}
  - { id: 431748264, name: "Pluralsight: Learn Tech Skills"}
  - { id: 1147396723, name: "WhatsApp Desktop" }
  - { id: 1099568401, name: "Home Assistant"}
  - { id: 425424353, name: "The Unarchiver"}

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A


# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
