---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Music
  - Notes
  - Reminders
  - Contacts
  - Calandar
  - Facetime
  - Photos
  - Maps
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

fonts:
  - name: Monoid
    archive: https://github.com/jb-dmitry/monoid.git
    version: master
    directory: Monoisome
    files:
      - Monoisome-Regular.ttf
  - name: Meslo LG M for Powerline
    archive: https://github.com/powerline/fonts.git
    version: master
    directory: "Meslo Slashed"
    files:
      - Meslo LG L Bold Italic for Powerline.ttf
      - Meslo LG L Bold for Powerline.ttf
      - Meslo LG L Italic for Powerline.ttf
      - Meslo LG L Regular for Powerline.ttf
      # - Meslo LG M Bold Italic for Powerline.ttf
      # - Meslo LG M Bold for Powerline.ttf
      # - Meslo LG M Italic for Powerline.ttf
      # - Meslo LG M Regular for Powerline.ttf
      # - Meslo LG S Bold Italic for Powerline.ttf
      # - Meslo LG S Bold for Powerline.ttf
      # - Meslo LG S Italic for Powerline.ttf
      # - Meslo LG S Regular for Powerline.ttf

dotfiles_repo: https://github.com/DamianFlynn/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Developer/dotfiles
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .aliases
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .aliases
  - .p10k.zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-versions
  - azure/bicep

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - age
  - ansible
  - autoconf
  - azure-cli
  - aztfy
  - bash-completion
  - bicep
  - brew-cask-completion
  - brotli
  - curl
  - direnv
  - diff-so-fancy
  - exiftool
  - fluxcd/tap/flux
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - gitleaks
  - go-task/tap/go-task
  - go
  - gpg
  - graphviz
  - httpie
  - helm
  - hugo
  - ipcalc
  - iperf
  - jq
  - k9s
  - kompose
  - kustomize
  - kubernetes-cli
  - mas
  - mcrypt
  - nmap
  - node
  - openssl
  - packer
  - pandoc
  - pre-commit
  - prettier
  - pv
  - readline
  - sops
  - ssh-copy-id
  - stern
  - telnet
  - terraform
  - tflint
  - tmux
  - wget
  - wrk
  - yamllint
  - yq
  - zsh-autosuggestions
  - zsh-history-substring-search

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password-beta
  - 1password-cli-beta
  - alfred
  - alt-tab
  - audacity
  - bartender
  - cheatsheet
  - discord
  - docker
  - drawio
  - elgato-stream-deck
  - elgato-wave-link
  - firefox
  - google-chrome
  - google-drive
  - hdhomerun
  - keyboard-maestro
  - logitech-options
  - microsoft-edge
  - microsoft-teams
  - miniconda
  - obsidian
  - obs-ndi
  - parallels-virtualization-sdk
  - plex
  - plexamp
  - powershell
  - spotify
  - vagrant
  - teamviewer
  - visual-studio-code
  - vlc
  - yubico-yubikey-manager
  # - yubico-authenticator
  # - yubico-yubikey-personalization-gui
  # - yubico-yubikey-piv-manager
  # - bose-updater
  

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 545519333, name: "Amazon Prime Video"}
  - { id: 431748264, name: "Pluralsight: Learn Tech Skills"}
  - { id: 1099568401, name: "Home Assistant"}
  - { id: 985367838, name: "Microsoft Outlook"}
  - { id: 823766827, name: "OneDrive"}
  - { id: 1295203466, name: "Microsoft Remote Desktop"}
  - { id: 784801555, name: "Microsoft OneNote"}
  - { id: 462062816, name:  "Microsoft PowerPoint"}
  - { id: 462058435, name: "Microsoft Excel"}
  - { id: 462054704, name: "Microsoft Word"}
  - { id: 1147396723, name: "WhatsApp Desktop" }
  - { id: 1455214828, name: "MQTT Explorer"}
  - { id: 425424353, name: "The Unarchiver"}
  - { id: 1290358394, name: "Cardhop"}
  - { id: 617187233, name: "iHelp"}
  - { id: 611021963, name: "SerialTools"}
  - { id: 1569813296, name: "1Password for Safari"}
  - { id: 975937182, name: "Fantastical - Calendar"}
  - { id: 1475387142, name: "Tailscale" }
  - { id: 1381004916, name: "Discovery - DNS-SD Browser"}

# reeder
# amphetamine
# bitwarden


mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A


# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
